######################################################################
# Automatically generated by qmake (2.01a) Mon Jan 9 21:04:27 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . \
              src \
              src/graphics \
              src/model \
              src/graphics/picture \
              src/graphics/tool \
              src/graphics/util \
              src/model/operation
INCLUDEPATH += . \
               src/graphics \
               src/model \
               src/graphics/picture \
               src/graphics/util \
               src/graphics/tool \
               src/model/operation

# Input
HEADERS += src/graphics/TabPanel.hh \
           src/graphics/TracingManager.hh \
           src/graphics/UserInterface.hh \
           src/model/Matrix.hh \
           src/model/Picture.hh \
           src/model/PixelMod.hh \
           src/model/Tracing.hh \
           src/model/Treatment.hh \
           src/graphics/picture/PictureButton.hh \
           src/graphics/picture/PictureManager.hh \
           src/graphics/picture/PictureModifier.hh \
           src/graphics/picture/PictureViewer.hh \
           src/graphics/tool/AffineOperationChooser.hh \
           src/graphics/tool/AlgebricOperationChooser.hh \
           src/graphics/tool/ColorChooser.hh \
           src/graphics/tool/ColorConvertOperationChooser.hh \
           src/graphics/tool/ConvolveOperationChooser.hh \
           src/graphics/tool/OperationChooser.hh \
           src/graphics/tool/RescaleOperationChooser.hh \
           src/graphics/tool/ToolMaker.hh \
           src/graphics/util/MPushButton.hh \
           src/graphics/util/MTabWidget.hh \
           src/model/operation/ColorConvertOperation.hh \
           src/model/operation/ConvolveOperation.hh \
           src/model/operation/MergeOperation.hh \
           src/model/operation/Operation.hh
SOURCES += src/Application.cc \
           src/graphics/TabPanel.cc \
           src/graphics/TracingManager.cc \
           src/graphics/UserInterface.cc \
           src/graphics/UserInterfaceAction.cc \
           src/graphics/UserInterfaceMenu.cc \
           src/graphics/UserInterfaceToolBar.cc \
           src/model/Picture.cc \
           src/model/Tracing.cc \
           src/model/Treatment.cc \
           src/graphics/picture/PictureButton.cc \
           src/graphics/picture/PictureManager.cc \
           src/graphics/picture/PictureModifier.cc \
           src/graphics/picture/PictureViewer.cc \
           src/graphics/tool/AffineOperationChooser.cc \
           src/graphics/tool/AlgebricOperationChooser.cc \
           src/graphics/tool/ColorChooser.cc \
           src/graphics/tool/ColorConvertOperationChooser.cc \
           src/graphics/tool/ConvolveOperationChooser.cc \
           src/graphics/tool/OperationChooser.cc \
           src/graphics/tool/RescaleOperationChooser.cc \
           src/graphics/tool/ToolMaker.cc \
           src/graphics/util/MPushButton.cc \
           src/graphics/util/MTabWidget.cc \
           src/model/operation/ColorConvertOperation.cc \
           src/model/operation/ConvolveOperation.cc \
           src/model/operation/MergeOperation.cc \
           src/model/operation/Operation.cc
